project_id = "ixvvowvzpwprjvwupwkm"

# API settings
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

# Auth settings
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

# Studio settings
[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

# Inbucket settings
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

# Storage settings
[storage]
enabled = true
file_size_limit = "50MiB"

# Functions
[functions.generate-resources]
verify_jwt = false

[functions.generate-assignment]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-presentations]
verify_jwt = false

# Database settings
[db]
major_version = 15